#!/usr/bin/python

import argparse
import hashtag
import ripoff

from pprint import pprint as pp


if __name__ == '__main__':

  parser = argparse.ArgumentParser()
  parser.add_argument('-q', '--query',       help='Search term',       default=None)
  parser.add_argument('-n', '--max-results', help='Number of results', default=25)
  parser.add_argument('-m', '--music',       help='Download music',    default=None, action="store_true")
  parser.add_argument('-i', '--input',       help='Input file',        default=None)
  #parser.add_argument('-f', '--file',        help='Database file',     default=None)
  args = parser.parse_args()

  if args.music:

     if args.query:
        songrows = ripoff.songs2rows([args.query]);
        hashtag.append_entries(songrows);

     elif args.input:
        inputfile = open(args.input)
        songs = inputfile.readlines();
        songs = [l.strip() for l in songs];
        songrows = ripoff.songs2rows(songs);

     musicdb = hashtag.parserows(songrows);
     ripoff.download_music(musicdb);
     hashtag.append_entries(songrows);

  else:

     if args.query:

        videos = ripoff.youtube_search(
          args.query,
          args.max_results
        );
        videos = ripoff.filter_downloaded(videos);
        videos = ripoff.vim_select(videos);
        ripoff.download_vids(
          ripoff.video_urls(videos)
        )
