#!/usr/bin/python

import argparse
import hashtag
import ripoff


if __name__ == '__main__':


  parser = argparse.ArgumentParser()
  parser.add_argument('-q', '--query',       help='Search term',       default=None)
  parser.add_argument('-n', '--max-results', help='Number of results', default=25)
  parser.add_argument('-m', '--music',       help='Download music',    default=None, action="store_true")
  parser.add_argument('-i', '--input',       help='Input file',        default=None)
  parser.add_argument('-f', '--file',        help='Database file',     default="database.tag")
  args = parser.parse_args()

  if args.music:
     rip = ripoff.YouTubeRipper(args.file);
     if args.query:
        songs = [args.query];
     elif args.input:
        inputfile = open(args.input)
        songs     = inputfile.readlines();
        songs     = [l.strip() for l in songs];
     rip.music(songs);
  else:
     if args.query:
        rip.vids(query)
