#!/usr/bin/python

import argparse
import hashtag
import ripoff


if __name__ == '__main__':


  parser = argparse.ArgumentParser()
  parser.add_argument('-q', '--query',       help='Search term',       default=None)
  parser.add_argument('-n', '--max-results', help='Number of results', default=25)
  parser.add_argument('-m', '--music',       help='Download music',    default=None, action="store_true")
  parser.add_argument('-i', '--input',       help='Input file',        default=None)
  #parser.add_argument('-f', '--file',        help='Database file',     default=None)
  args = parser.parse_args()


  if args.music:

     ht  = hashtag.HashTagger();
     rip = ripoff.YouTubeRipper();

     if args.query:
        songrows = rip.songs2rows([args.query]);
        ht.append_entries(songrows);

     elif args.input:
        inputfile = open(args.input)
        songs     = inputfile.readlines();
        songs     = [l.strip() for l in songs];
        songrows  = rip.songs2rows(songs);

     musicdb = ht.parserows(songrows);
     rip.download_music(musicdb);
     ht.append_entries(songrows);


  else:

     if args.query:
        videos = rip.youtube_search(
          args.query,
          args.max_results
        );
        videos = rip.filter_downloaded(videos);
        videos = rip.vim_select(videos);
        rip.download_vids(
          rip.video_urls(videos)
        )
