#!/usr/bin/python

import hashtag
import smartlog
import mplayer
import time
import code


class HashtagPlayer(mplayer.Player):

    log = smartlog.Smartlog();
    playlist = [];

    def __init__(self):
        args = "-ao alsa:device=default"
        super().__init__(args);

    def is_running(self):
        if self.filepath: return True;
        else:             return False;

    def play(self, path):
        self.loadfile(path);
        if self.paused:
           self.pause();
        while self.is_running():
              time.sleep(1); 

    def interpret(self):
        while True:
              x = log.gather(['command']);

    

htp = HashtagPlayer();
path = "/home/dominic/mus/electronic/dj-icey/reflex-speed.mp3"
htp.play(path);

